/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: phuson (https://sketchfab.com/phuson)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/tosilog-a-tasty-filipino-breakfast-16ed9fbde35746588456149d7c14588d
title: TOSILOG - a tasty Filipino breakfast!
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/masalarice.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={8}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials.splating2} />
        </group>
      </group>
    </group>
  ) 
}

useGLTF.preload('/masalarice.gltf')
